version: 0.2

env:
  parameter-store:
    DOCKER_HUB_USERNAME: "docker-hub-username"
    DOCKER_HUB_PASSWORD: "docker-hub-password"
    GITHUB_USERNAME: "agonyforge-github-packages-username"
    GITHUB_TOKEN: "agonyforge-github-packages-token"

phases:
  install:
    commands:
      - chmod +x ./gradlew
  pre_build:
    commands:
      - docker login -u ${DOCKER_HUB_USERNAME} -p ${DOCKER_HUB_PASSWORD}
      - docker login ghcr.io -u ${GITHUB_USERNAME} -p ${GITHUB_TOKEN}
      - export PROJECT_VERSION=v`egrep "^version" build.gradle | cut -f2 -d\'`
      - export BRANCH_TAG=`echo ${CODEBUILD_SOURCE_VERSION} | sed 's|/|-|g'`
      - echo "Codebuild initiator is ${CODEBUILD_INITIATOR}"
      - echo "Branch is ${BRANCH_TAG}"
      - echo "Project version is ${PROJECT_VERSION}"
  build:
    commands:
      - ./gradlew clean build --info --stacktrace
  post_build:
    commands:
      - |
        if expr "${CODEBUILD_INITIATOR}" : "codepipeline*" >/dev/null; then
          echo "publishing JARs to GitHub"
        
          ./gradlew publish
        
          echo "pushing SNAPSHOT container to GitHub"
        
          docker tag scionaltera/brave4j:latest scionaltera/brave4j:${PROJECT_VERSION}
          docker tag scionaltera/brave4j:latest ghcr.io/scionaltera/brave4j:${PROJECT_VERSION}
        
          docker push ghcr.io/scionaltera/brave4j:${PROJECT_VERSION}
        
          if expr "${PROJECT_VERSION}" : "^v[0-9.]+$" >/dev/null; then  
            echo "pushing RELEASE container to GitHub"
        
            docker tag scionaltera/brave4j:latest ghcr.io/scionaltera/brave4j:latest            
        
            docker push ghcr.io/scionaltera/brave4j:latest
          fi              
        fi
